' Gambas module file

PUBLIC FUNCTION Get_Conf(tmpStr AS String) AS Variant
  DIM sLine, Result AS String
  DIM hFile AS File
  
  hFile = OPEN "/opt/Customizer/settings.conf" FOR INPUT 
  WHILE NOT Eof(hFile)
    LINE INPUT #hFile, sLine
    IF sLine LIKE tmpStr & "*" THEN 
      sLine = Replace$(sLine, "\"", "")
      Result = Replace$(sLine, tmpStr, "")
      BREAK 
    ENDIF 
  WEND
  
  RETURN Result

  CATCH 
    Message.Error("Unable to get value: " & tmpStr)
END

PUBLIC FUNCTION Get_Str(tmpFile AS String, tmpStr AS String) AS Variant
  DIM sLine, WorkDir, Result AS String
  DIM hFile AS File

  hFile = OPEN tmpFile FOR INPUT 
  WHILE NOT Eof(hFile)
    LINE INPUT #hFile, sLine
    IF sLine LIKE "*" & tmpStr & "*" THEN 
      sLine = Replace$(sLine, "\"", "")
      sLine = Replace$(sLine, "export ", "")
      Result = Replace$(sLine, tmpStr, "")
      BREAK 
    ENDIF 
  WEND
  
  RETURN Result

  CATCH 
    Message.Error("Unable to get info!\n\nFile: " & tmpFile & "\nString: " & tmpStr)
END
