' Gambas module file

PUBLIC SUB Browse_FileSystem_Folder()
  DIM WorkDir, tmpStr AS String

  tmpStr = "WORK_DIR="
  WorkDir = Functions.Get_Conf(tmpStr)
  
  IF Exist("/usr/bin/nautilus") THEN 
    EXEC ["/usr/bin/nautilus", WorkDir & "/ISO"]
  ELSE IF Exist("/usr/bin/dolphin") THEN 
    EXEC ["/usr/bin/dolphin", WorkDir & "/ISO"]
  ELSE IF Exist("/usr/bin/pcmanfm") THEN 
    EXEC ["/usr/bin/pcmanfm", WorkDir & "/ISO"]
  ELSE IF Exist("/usr/bin/xfe") THEN 
    EXEC ["/usr/bin/xfe", WorkDir & "/ISO"]
  ELSE IF Exist("/usr/bin/worker") THEN 
    EXEC ["/usr/bin/worker", WorkDir & "/ISO"]
  ELSE IF Exist("/usr/bin/gentoo") THEN 
    EXEC ["/usr/bin/gentoo", WorkDir & "/ISO"]
  ELSE IF Exist("/usr/bin/thunar") THEN 
    EXEC ["/usr/bin/thunar", WorkDir & "/ISO"]
  ELSE IF Exist("/usr/bin/filerunner") THEN 
    EXEC ["/usr/bin/filerunner", WorkDir & "/ISO"]
  ELSE IF Exist("/usr/bin/krusader") THEN 
    EXEC ["/usr/bin/krusader", WorkDir & "/ISO"]
  ELSE IF Exist("/usr/bin/rox-filer") THEN 
    EXEC ["/usr/bin/rox-filer", WorkDir & "/ISO"]
  ELSE 
    Message.Warning("No supported File-Manager was detected! \nSupported File-Managers are: \n\n<b>Nautilus (Gnome) \nDolphin (KDE) \n PCManFM (LXDE) \nThunar (XFCE4) \nXFE \nWorker \nGentoo \nFileRunner \nKrusader \nROX-Filer</b> \n\n Next time you try to browse folders \nmake sure you've installed one of these.")
  ENDIF
END

PUBLIC SUB Browse_ISO_Folder()
  DIM WorkDir, tmpStr AS String

  tmpStr = "WORK_DIR="
  WorkDir = Functions.Get_Conf(tmpStr)

  IF Exist("/usr/bin/nautilus") THEN 
    EXEC ["/usr/bin/nautilus", WorkDir & "/ISO"]
  ELSE IF Exist("/usr/bin/dolphin") THEN 
    EXEC ["/usr/bin/dolphin", WorkDir & "/ISO"]
  ELSE IF Exist("/usr/bin/pcmanfm") THEN 
    EXEC ["/usr/bin/pcmanfm", WorkDir & "/ISO"]
  ELSE IF Exist("/usr/bin/xfe") THEN 
    EXEC ["/usr/bin/xfe", WorkDir & "/ISO"]
  ELSE IF Exist("/usr/bin/worker") THEN 
    EXEC ["/usr/bin/worker", WorkDir & "/ISO"]
  ELSE IF Exist("/usr/bin/gentoo") THEN 
    EXEC ["/usr/bin/gentoo", WorkDir & "/ISO"]
  ELSE IF Exist("/usr/bin/thunar") THEN 
    EXEC ["/usr/bin/thunar", WorkDir & "/ISO"]
  ELSE IF Exist("/usr/bin/filerunner") THEN 
    EXEC ["/usr/bin/filerunner", WorkDir & "/ISO"]
  ELSE IF Exist("/usr/bin/krusader") THEN 
    EXEC ["/usr/bin/krusader", WorkDir & "/ISO"]
  ELSE IF Exist("/usr/bin/rox-filer") THEN 
    EXEC ["/usr/bin/rox-filer", WorkDir & "/ISO"]
  ELSE 
    Message.Warning("No supported File-Manager was detected! \nSupported File-Managers are: \n\n<b>Nautilus (Gnome) \nDolphin (KDE) \n PCManFM (LXDE) \nThunar (XFCE4) \nXFE \nWorker \nGentoo \nFileRunner \nKrusader \nROX-Filer</b> \n\n Next time you try to browse folders \nmake sure you've installed one of these.")
  ENDIF
END

PUBLIC SUB Enable_Stuff()
  FMain.Create_Snapshot.Enabled = TRUE
  FMain.Edit_Sources.Enabled = TRUE
  FMain.Install_DEB.Enabled = TRUE
  FMain.Terminal.Enabled = TRUE
  FMain.Build_ISO.Enabled = TRUE
  FMain.Clean.Enabled = TRUE
  FMain.Extras_Menu.Enabled = TRUE
  FMain.Archive.Enabled = TRUE
  FMain.DistName.Enabled = TRUE
  FMain.HostName.Enabled = TRUE
  FMain.LiveCD_User.Enabled = TRUE
  FMain.Version.Enabled = TRUE
  FMain.ReleaseNotesURL.Enabled = TRUE
  
  'Check for installed Desktop env. or Window Manager
  Check.X_session()
  Check.Pkg_Manager()
END

PUBLIC SUB Disable_Stuff()
  FMain.Create_Snapshot.Enabled = FALSE
  FMain.Edit_Sources.Enabled = FALSE
  FMain.Install_DEB.Enabled = FALSE
  FMain.Archive.Enabled = FALSE
  FMain.Terminal.Enabled = FALSE
  FMain.Build_ISO.Enabled = FALSE
  FMain.Clean.Enabled = FALSE
  FMain.Extras_Menu.Enabled = FALSE
  FMain.Desktop.Enabled = FALSE
  
  FMain.DistName.Enabled = FALSE
  FMain.HostName.Enabled = FALSE
  FMain.LiveCD_User.Enabled = FALSE
  FMain.Version.Enabled = FALSE
  FMain.ReleaseNotesURL.Enabled = FALSE
END
