' Gambas module file

PUBLIC SUB Browse_FileSystem_Folder()
  DIM FILEMANAGER, WorkDir, tmpStr AS String

  tmpStr = "WORK_DIR="
  WorkDir = Functions.Get_Conf(tmpStr)
  
  IF Exist("/usr/bin/nautilus") THEN 
    FILEMANAGER = "nautilus"
  ENDIF 
  
  IF Exist("/usr/bin/dolphin") THEN 
    FILEMANAGER = "dolphin"
  ENDIF
  
  IF Exist("/usr/bin/pcmanfm") THEN 
    FILEMANAGER = "pcmanfm"
  ENDIF
  
  IF Exist("/usr/bin/xfe") THEN 
    FILEMANAGER = "xfe"
  ENDIF
  
  IF Exist("/usr/bin/worker") THEN 
    FILEMANAGER = "worker"
  ENDIF
  
  IF Exist("/usr/bin/gentoo") THEN 
    FILEMANAGER = "gentoo"
  ENDIF
  
  IF Exist("/usr/bin/thunar") THEN 
    FILEMANAGER = "thunar"
  ENDIF
  
  
  IF Exist("/usr/bin/filerunner") THEN 
    FILEMANAGER = "filerunner"
  ENDIF
  
  IF Exist("/usr/bin/krusader") THEN 
    FILEMANAGER = "krusader"
  ENDIF
  
  IF Exist("/usr/bin/rox-filer") THEN 
    FILEMANAGER = "rox-filer"
  ENDIF
  
  IF NOT Exist("/usr/bin/nautilus") AND IF NOT Exist("/usr/bin/dolphin") AND IF NOT Exist("/usr/bin/pcmanfm") AND IF NOT Exist("/usr/bin/xfe") AND IF NOT Exist("/usr/bin/worker") AND IF NOT Exist("/usr/bin/gentoo") AND IF NOT Exist("/usr/bin/thunar") AND IF NOT Exist("/usr/bin/filerunner") AND IF NOT Exist("/usr/bin/krusader") AND IF NOT Exist("/usr/bin/rox-filer") THEN
    Message.Warning("No supported File-Manager was detected! \nSupported File-Managers are: \n\n<b>Nautilus (Gnome) \nDolphin (KDE) \n PCManFM (LXDE) \nThunar (XFCE4) \nXFE \nWorker \nGentoo \nFileRunner \nKrusader \nROX-Filer</b> \n\n Next time you try to browse folders \nmake sure you've installed one of these.")
  ELSE 
    EXEC [FILEMANAGER, WorkDir & "/FileSystem"]
  ENDIF 
END

PUBLIC SUB Browse_ISO_Folder()
  DIM FILEMANAGER, WorkDir, tmpStr AS String

  tmpStr = "WORK_DIR="
  WorkDir = Functions.Get_Conf(tmpStr)
  
  IF Exist("/usr/bin/nautilus") THEN 
    FILEMANAGER = "nautilus"
  ENDIF 
  
  IF Exist("/usr/bin/dolphin") THEN 
    FILEMANAGER = "dolphin"
  ENDIF
  
  IF Exist("/usr/bin/pcmanfm") THEN 
    FILEMANAGER = "pcmanfm"
  ENDIF
  
  IF Exist("/usr/bin/xfe") THEN 
    FILEMANAGER = "xfe"
  ENDIF
  
  IF Exist("/usr/bin/worker") THEN 
    FILEMANAGER = "worker"
  ENDIF
  
  IF Exist("/usr/bin/gentoo") THEN 
    FILEMANAGER = "gentoo"
  ENDIF
  
  IF Exist("/usr/bin/thunar") THEN 
    FILEMANAGER = "thunar"
  ENDIF
  
  
  IF Exist("/usr/bin/filerunner") THEN 
    FILEMANAGER = "filerunner"
  ENDIF
  
  IF Exist("/usr/bin/krusader") THEN 
    FILEMANAGER = "krusader"
  ENDIF
  
  IF Exist("/usr/bin/rox-filer") THEN 
    FILEMANAGER = "rox-filer"
  ENDIF
  
  IF NOT Exist("/usr/bin/nautilus") AND IF NOT Exist("/usr/bin/dolphin") AND IF NOT Exist("/usr/bin/pcmanfm") AND IF NOT Exist("/usr/bin/xfe") AND IF NOT Exist("/usr/bin/worker") AND IF NOT Exist("/usr/bin/gentoo") AND IF NOT Exist("/usr/bin/thunar") AND IF NOT Exist("/usr/bin/filerunner") AND IF NOT Exist("/usr/bin/krusader") AND IF NOT Exist("/usr/bin/rox-filer") THEN
    Message.Warning("No supported File-Manager was detected! \nSupported File-Managers are: \n\n<b>Nautilus (Gnome) \nDolphin (KDE) \n PCManFM (LXDE) \nThunar (XFCE4) \nXFE \nWorker \nGentoo \nFileRunner \nKrusader \nROX-Filer</b> \n\n Next time you try to browse folders \nmake sure you've installed one of these.")
  ELSE 
    EXEC [FILEMANAGER, WorkDir & "/ISO"]
  ENDIF 
END

PUBLIC SUB Enable_Stuff()
  FMain.Create_Snapshot.Enabled = TRUE
  FMain.Edit_Sources.Enabled = TRUE
  FMain.Install_DEB.Enabled = TRUE
  FMain.Terminal.Enabled = TRUE
  FMain.Build_ISO.Enabled = TRUE
  FMain.Clean.Enabled = TRUE
  FMain.Extras_Menu.Enabled = TRUE
  FMain.Archive.Enabled = TRUE
  FMain.DistName.Enabled = TRUE
  FMain.HostName.Enabled = TRUE
  FMain.LiveCD_User.Enabled = TRUE
  FMain.Version.Enabled = TRUE
  FMain.ReleaseNotesURL.Enabled = TRUE
  
  'Check for installed Desktop env. or Window Manager
  Check.X_session()
  Check.Pkg_Manager()
END

PUBLIC SUB Disable_Stuff()
  FMain.Create_Snapshot.Enabled = FALSE
  FMain.Edit_Sources.Enabled = FALSE
  FMain.Install_DEB.Enabled = FALSE
  FMain.Archive.Enabled = FALSE
  FMain.Terminal.Enabled = FALSE
  FMain.Build_ISO.Enabled = FALSE
  FMain.Clean.Enabled = FALSE
  FMain.Extras_Menu.Enabled = FALSE
  FMain.Desktop.Enabled = FALSE
  
  FMain.DistName.Enabled = FALSE
  FMain.HostName.Enabled = FALSE
  FMain.LiveCD_User.Enabled = FALSE
  FMain.Version.Enabled = FALSE
  FMain.ReleaseNotesURL.Enabled = FALSE
END