#!/usr/bin/env bash
# Customizer - Advanced LiveCD Remastering Tool
# Copyright (C) 2010-2012  Ivailo Monev
# 
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
#
# Homepage: https://github.com/fluxer/Customizer
# Wiki: https://github.com/fluxer/Customizer/wiki
# Issues: https://github.com/fluxer/Customizer/issues
#
set -u
source /opt/Customizer/libs/source.lib
source /opt/Customizer/settings.conf

CHECK_UID
CHECK_FILESYSTEM

if [ ! -e "$DEB" ];then
	ERROR "DEB package doesn't exists"
fi

case "$DEB" in
	*.deb) rm -f "$FILESYSTEM_DIR/FileSystem/tmp/*.deb"
           cp -f "$DEB" "$FILESYSTEM_DIR/FileSystem/tmp" ;;
	*) ERROR "This is not DEB package" ;;
esac

CHROOT_PREPARE
CHROOT_MOUNT_PSEUDO
CHROOT_FIX
CHROOT_HELPER
EXTRA_INFO "Installing deb package" "$(basename $DEB)"
CHROOT_EXECUTE "dpkg -i /tmp/*.deb"
INFO "Installing dependencies for the package"
CHROOT_EXECUTE "apt-get install -f -y"
CHROOT_UNDO_FIX
CHROOT_UNMOUNT_PSEUDO
CHROOT_VERB_UNMOUNT_PSEUDO
CHROOT_CLEAN