#!/usr/bin/env bash
# Customizer - Advanced LiveCD Remastering Tool
# Copyright (C) 2010-2012  Ivailo Monev
# 
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
#
# Homepage: https://github.com/fluxer/Customizer
# Wiki: https://github.com/fluxer/Customizer/wiki
# Issues: https://github.com/fluxer/Customizer/issues
#
source /opt/Customizer/settings.conf
source /opt/Customizer/libs/source.lib

set +x
MOUNT_DIR="$(mktemp -d --tmpdir="$MOUNT_DIR")"

#################### Some functions used when error accures #####################

_CLEAN_() {
    umount -fl "$MOUNT_DIR" 2> /dev/null
    INFO "Purging working direcotries"
    for i in "$FILESYSTEM_DIR" "$ISO_DIR" "$MOUNT_DIR";do
	    EXTRA_DEBUG "$i"
	    rm -rf "$i" || EXTRA_ERROR "Unable to purge" "$i"
    done
}

########### Checking and cleaning up previous temp folders if exists ############

if [ -z "$ISO" ];then
	ERROR '$ISO is null'
elif [ ! -e "$ISO" ];then
	ERROR "The ISO image doesn't exists."
elif [ -d "$FILESYSTEM_DIR" ] || [ -d "$ISO_DIR" ];then
    _CLEAN_

    INFO "Creating work directories"
    mkdir -p "$FILESYSTEM_DIR" "$ISO_DIR" "$MOUNT_DIR" || ERROR "Unable to create the working directories"
else
    INFO "Creating work directories"
    mkdir -p "$FILESYSTEM_DIR" "$ISO_DIR" "$MOUNT_DIR" || ERROR "Unable to create the working directories"
fi

############################# Mounting the ISO image #############################

INFO "Mounting ISO"
mount -t iso9660 -o ro,loop "$ISO" "$MOUNT_DIR" || ERROR "Unable to mount the ISO"

######################## Check if the ISO image is usable ########################

INFO "Checking ISO image"
if [ ! -d "$MOUNT_DIR/casper" ] || [ ! -d "$MOUNT_DIR/.disk" ] || \
 [ ! -d "$MOUNT_DIR/isolinux" ] || [ ! -e "$MOUNT_DIR/casper/filesystem.squashfs" ]; then
    umount -fl "$MOUNT_DIR" 2> /dev/null
    INFO "Purging working direcotries"
    for i in "$FILESYSTEM_DIR" "$ISO_DIR" "$MOUNT_DIR";do
	      EXTRA_DEBUG "$i"
	      rm -rf "$i" || EXTRA_ERROR "Unable to purge" "$i"
    done
    ERROR "This is not a usable ISO image"
fi

######################### Extraction filesystem.squashfs ##########################

INFO "Extracting FileSystem"
unsquashfs -f -d "$FILESYSTEM_DIR" "$MOUNT_DIR/casper/filesystem.squashfs" || ERROR "Unable to extract the filesystem.squashfs"

################## Check the architecture of the root filesystem ##################

INFO "Checking architecture"
ARCH="$(chroot "$FILESYSTEM_DIR" dpkg --print-architecture)" || ERROR "Unable to chroot and get the architecture"
if [ "$ARCH" = "amd64" -o "" ] && [ "$(uname -m)" != "x86_64" ]; then
    _CLEAN__
    ERROR "The ISOs architecture is amd64 and yours is not"
fi


############ rsync the some files but exclude some that are not needed ############

INFO "Copying ISO files"
rsync --exclude=/casper/* --exclude=/md5sum.txt --exclude=/README.diskdefines -a "$MOUNT_DIR/" "$ISO_DIR" || ERROR "Unable to rsync files"

############################## Unmount the ISO image ##############################
INFO "Unmounting ISO"
umount -f "$MOUNT_DIR" || EXTRA_ERROR "Unable to unmount the ISO from" "$MOUNT_DIR"
rm -rf "$MOUNT_DIR"
