#!/usr/bin/env bash
# Customizer - Advanced LiveCD Remastering Tool
# Copyright (C) 2010-2013  Ivailo Monev
# 
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
#
# Homepage: https://github.com/fluxer/Customizer
# Wiki: https://github.com/fluxer/Customizer/wiki
# Issues: https://github.com/fluxer/Customizer/issues
#
set -u
source /opt/Customizer/common
source /opt/Customizer/settings.conf

__check_fs_dir__
__check_lock__
__check_sources_list__

WARNING_MESSAGE "ONLY THE BARE MINIMUM SET OF PACKAGES WILL BE INSTALLED!"
while true;do
	echo "
	1. Gnome2
	2. Unity
	3. KDE
	4. XFCE4
	5. LXDE
	6. Openbox
	7. Fluxbox
	8. Blackbox
	9. IceWM"
	echo
	EXTRA_QUESTION_MESSAGE "Which GUI do you want to install?" "1-9"
	read choise
    
    case $choise in
        1) GUI_PACKAGES="xserver-xorg xinit gnome-session gnome-panel gdm gnome-terminal gtk2-engines gnome-themes-selected"; break ;;
        2) GUI_PACKAGES="xserver-xorg xinit unity unity-2d gnome-session gnome-terminal gnome-icon-theme"; break ;;
	3) GUI_PACKAGES="xserver-xorg xinit kde-standard"; break ;;
        # TODO: xfce4-session xfce4-panel xfce4-terminal
        4) GUI_PACKAGES="xserver-xorg xinit xfce4-panel xfce4-session xfwm4 xfdesktop4 xfce4-terminal thunar xfce4-utils"; break ;;
        5) GUI_PACKAGES="xserver-xorg xinit lxde-core lxterminal lxdm"; break ;;
        6) GUI_PACKAGES="xserver-xorg xinit xterm openbox menu slim"; break ;;
        7) GUI_PACKAGES="xserver-xorg xinit xterm fluxbox menu slim"; break ;;
        8) GUI_PACKAGES="xserver-xorg xinit xterm blackbox menu slim"; break ;;
        9) GUI_PACKAGES="xserver-xorg xinit icewm-lite menu xdm"; break ;;
        *) WARNING_MESSAGE "This is not an option" ;;
    esac
done

__mount_sys__
__mount_dbus__
__chroot__ apt-get install dbus -f -y
__chroot__ dbus-uuidgen --ensure
__chroot__ apt-get install -y ${GUI_PACKAGES} --no-install-recommends
__umount_sys__
__recursive_umount__
