#!/usr/bin/env bash
# Customizer - Advanced LiveCD Remastering Tool
# Copyright (C) 2010-2012  Ivailo Monev
# 
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
#
# Homepage: https://github.com/fluxer/Customizer
# Wiki: https://github.com/fluxer/Customizer/wiki
# Issues: https://github.com/fluxer/Customizer/issues
#
set -u
source /opt/Customizer/settings.conf
source /opt/Customizer/libs/source.lib

CHECK_UID
CHECK_FILESYSTEM

if [ ! -e "$HOOK" ];then
	ERROR "The hook files doesn't exists"
else
    cp -f "$HOOK" "$FILESYSTEM_DIR/tmp/HOOK"
    chmod +x "$$FILESYSTEM_DIR/tmp/HOOK"
fi

CHROOT_PREPARE
CHROOT_MOUNT_PSEUDO
CHROOT_FIX
CHROOT_HELPER
ALLOW_LOCAL_X
INFO "Executing chroot hook" "$(basename $HOOK)"
CHROOT_EXECUTE "exec /tmp/HOOK"
BLOCK_LOCAL_X
CHROOT_UNDO_FIX
CHROOT_UNMOUNT_PSEUDO
CHROOT_VERB_UNMOUNT_PSEUDO
CHROOT_CLEAN