#!/usr/bin/env bash
# Customizer - Advanced LiveCD Remastering Tool
# Copyright (C) 2010-2012  Ivailo Monev
# 
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
#
# Homepage: https://github.com/fluxer/Customizer
# Wiki: https://github.com/fluxer/Customizer/wiki
# Issues: https://github.com/fluxer/Customizer/issues
#
set -u
source /opt/Customizer/libs/source.lib
source /opt/Customizer/settings.conf

__check_fs_dir__
__check_lock__
__check_sources_list__

if [ ! -e "$DEB" ];then
	ERROR "DEB package doesn't exists"
fi

case "$DEB" in
	*.deb) cp -f "$DEB" "$WORK_DIR/FileSystem/tmp" ;;
	*) ERROR "This is not DEB package" ;;
esac

__allow_local_X_access__
__mount_sys__
__chroot__ "dpkg -i /tmp/*.deb; apt-get install -f -y"
__umount_sys__
__recursive_umount__
__block_local_X_access__
