#!/usr/bin/env bash
# Customizer - Advanced LiveCD Remastering Tool
# Copyright (C) 2010-2012  Ivailo Monev
# 
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
#
# Homepage: https://github.com/fluxer/Customizer
# Wiki: https://github.com/fluxer/Customizer/wiki
# Issues: https://github.com/fluxer/Customizer/issues
#
set -u
source /opt/Customizer/common
source /opt/Customizer/settings.conf

__check_fs_dir__
__check_lock__
__check_sources_list__

INFO_MESSAGE "Detecting package manager"
if [ -e "$WORK_DIR/FileSystem/usr/sbin/synaptic" ];then
	# __check_for_X__
	PKGM="synaptic"
	EXTRA_INFO_MESSAGE "Will run" "$PKGM"
elif [ -e "$WORK_DIR/FileSystem/usr/bin/aptitude" ];then
	PKGM="aptitude"
	EXTRA_INFO_MESSAGE "Will run" "$PKGM"
else
	ERROR_MESSAGE "No supported package managers were detected"
fi

__allow_local_X_access__
__mount_sys__
__mount_dbus__
__chroot__ apt-get install dbus -y -f
__chroot__ dbus-uuidgen --ensure
__chroot__ $PKGM
__umount_sys__
__recursive_umount__
__block_local_X_access__
