#!/usr/bin/env bash
# Customizer - Advanced LiveCD Remastering Tool
# Copyright (C) 2011  Ivailo Monev
# 
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
#
# Homepage: https://github.com/fluxer/Customizer
# Wiki: https://github.com/fluxer/Customizer/wiki
# Issues: https://github.com/fluxer/Customizer/issues
#
set -u
source /opt/Customizer/common
source /opt/Customizer/settings.conf

__check_for_X__

INFO_MESSAGE "Getting the configs"
ARCH=`chroot "$WORK_DIR/FileSystem" dpkg --print-architecture` || ERROR_MESSAGE "Unable to chroot and get the architecture"
DIST=`grep DISTRIB_ID= "$WORK_DIR/FileSystem/etc/lsb-release" | sed 's/DISTRIB_ID=/;s/\"//g/'` || ERROR_MESSAGE "Unable to get the distribution ID"
VERSION=`grep DISTRIB_RELEASE= "$WORK_DIR/FileSystem/etc/lsb-release" | sed 's/DISTRIB_RELEASE=//;s/\"//g'` || ERROR_MESSAGE "Unable to get the distribution version"

if [ ! -e "$WORK_DIR/$DIST-$ARCH-$VERSION.iso" ];then
	EXTRA_ERROR_MESSAGE "ISO Image doesn't exists" "$WORK_DIR/$DIST-$ARCH-$VERSION.iso"
else
	EXTRA_INFO_MESSAGE "Running QEMU with ISO image" "$WORK_DIR/$DIST-$ARCH-$VERSION.iso"
	if [ "`dpkg --print-architecture`" = "amd64" ];then
		qemu-system-x86_64 -cdrom "$WORK_DIR/$DIST-$ARCH-$VERSION.iso" -m $VRAM || ERROR_MESSAGE "An error accure while trying to emulate the ISO"	
	else
		qemu -cdrom "$WORK_DIR/$DIST-$ARCH-$VERSION.iso" -m $VRAM || ERROR_MESSAGE "An error accure while trying to emulate the ISO"	
	fi
fi

