#!/usr/bin/env bash
# Customizer - Advanced LiveCD Remastering Tool
# Copyright (C) 2011  Ivailo Monev
# 
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
#
# Homepage: https://github.com/fluxer/Customizer
# Wiki: https://github.com/fluxer/Customizer/wiki
# Issues: https://github.com/fluxer/Customizer/issues
#
set -u
source /opt/Customizer/common
source /opt/Customizer/settings.conf

__check_for_X__
__check_fs_dir__
__check_lock__
__check_sources_list__

AVAILABLE=`(ls "$WORK_DIR/FileSystem/usr/share/xsessions" | wc -l) 2> /dev/null`
case $AVAILABLE in
	0) ERROR_MESSAGE "There are not X-session available" ;;
	1) choise="`ls -F "$WORK_DIR/FileSystem/usr/share/xsessions" | sed 's/\.desktop//'`"
	   EXTRA_WARNING_MESSAGE "There is only one X-session available" "$choise" ;;
	*) WARNING_MESSAGE "Multiple X-sessions available, choose which one to execute:"
	
	while true;do
	echo
	for i in `ls "$WORK_DIR/FileSystem/usr/share/xsessions" | sed 's/.desktop//'`;do
		echo -e "${Green}$i${Reset}"
	done
	
	echo
	echo -ne "${Yellow}What shall it be?${Reset}: "
	read choise
	
	if [ ! -e "$WORK_DIR/FileSystem/usr/share/xsessions/$choise.desktop" ];then
		ERROR_MESSAGE_NO_EXIT "This is not an option"	
	else
		break
	fi
	done ;;
esac

# Start Xephyr and the script
# FIXME: error not shown when unable to execute Xephyr
# (Xephyr -ac -screen $RESOLUTION -br :9 &) || xephyr_error
INFO_MESSAGE "Starting Xephyr"
Xephyr -ac -screen $RESOLUTION -br :9 &

__allow_local_X_access__
__mount_sys__
__mount_dbus__
__chroot__ "apt-get install dbus -y -f
export DISPLAY=localhost:9
dbus-uuidgen --ensure

`grep -m 1 "Exec=" /usr/share/xsessions/$choise.desktop | sed 's/Exec=//'`"
__umount_sys__
__recursive_umount__
__block_local_X_access__

INFO_MESSAGE "Stoping Xephyr"
killall Xephyr

INFO_MESSAGE "Remove some unwanted files/dirs"
rm -rf "$WORK_DIR/FileSystem/root/.kde/share/apps/nepomuk"
rm -rf "$WORK_DIR/FileSystem/root/.cache"
rm -rf "$WORK_DIR/FileSystem/root/.dbus"
rm -rf "$WORK_DIR/FileSystem/root/.thumbnails"

INFO_MESSAGE "Copying the changes to skel"
cp -ru "$WORK_DIR/FileSystem/root/"* "$WORK_DIR/FileSystem/etc/skel" 2> /dev/null
cp -ru "$WORK_DIR/FileSystem/root/".??* "$WORK_DIR/FileSystem/etc/skel" 2> /dev/null
